plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.planitsquare'
version = '0.0.1-SNAPSHOT'
description = 'medIngestEx'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url "https://www.dcm4che.org/maven2" }
    maven { url "https://raw.github.com/nroduit/mvn-repo/master/" }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-batch-jdbc'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-batch-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-batch-test'
    runtimeOnly 'org.postgresql:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // dcm4che DICOM Toolkit & Library
    implementation 'org.dcm4che:dcm4che-core:5.34.1'
    implementation 'org.dcm4che.tool:dcm4che-tool-common:5.34.1'
    implementation 'org.dcm4che.tool:dcm4che-tool-dcm2json:5.34.1'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    def envFile = file('.env')
    if (envFile.exists()) {
        envFile.readLines().each { line ->
            if (line && !line.startsWith('#') && line.contains('=')) {
                def (key, value) = line.split('=', 2)
                environment key.trim(), value.trim()
            }
        }
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        html.required = true
    }
}

tasks.named('bootRun') {
    def envFile = file('.env')
    if (envFile.exists()) {
        envFile.readLines().each { line ->
            if (line && !line.startsWith('#') && line.contains('=')) {
                def (key, value) = line.split('=', 2)
                environment key.trim(), value.trim()
            }
        }
    }
}
